FROM 52.63.34.52:5000/bwce:latest
MAINTAINER eschweit@tibco.com 
COPY resources/mysql-connector-java-5.1.42-bin.jar /resources/addons/jars
ADD tibco.bwce.sample.binding.rest.BookStore.application_1.0.0.ear /
EXPOSE 8080
